name: Test
description: Test adapter
node_identifier: test
platforms:
  - Docker
data_sources:
  - name: Binance
    url: https://binance.com
  - name: Coinbase Pro
    url: https://pro.coinbase.com
parameters:
  - url
  - copyPath
  - times
